# fly.toml app configuration file generated for reactivities-planner on 2023-10-20T10:44:52-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dotnet-react-eventure"
primary_region = "lax"

[env]
  ASPNETCORE_URLS="http://+:8080"
  Cloudinary__CloudName="doeosqsqu"
  Cloudinary__ApiKey="829112739361451"
  TokenKey="super secret key"
  DATABASE_URL="postgresql://reactivities-planner-db.flycast"

[build]
  image = "dayosql/reactivities:latest"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
